x-common-volumes: &common-volumes
  type: bind
  source: ./shared
  target: /shared

x-common-internal-service: &common-internal-service
  build:
    context: .
    dockerfile: Dockerfile.base
  volumes:
    - <<: *common-volumes

x-common-external-service: &common-external-service
  env_file:
    - .env
  volumes:
    - <<: *common-volumes

services:
  rest-server:
    <<: *common-internal-service
    command: python -m brain_computer_interface.rest run-rest-server -d postgresql://${POSTGRES_USER?err}:${POSTGRES_PASSWORD?err}@${POSTGRES_HOST?err}:5432/mind
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    <<: *common-external-service
    image: postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
