name: Generate coverage report

on: [push]
  # pull_request:
  #   types:
  #     - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Create python environment and install dependencies
      run: ./scripts/install.sh
    - name: Test with pytest
      run: ./scripts/test.sh
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
