name: Python package testing

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create python environment and install dependencies
        run: ./scripts/install.sh
      - name: Test with pytest
        run: ./scripts/test.sh
