name: Python package testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Create python environment and install dependencies
      run: ./scripts/install.sh
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 brain_computer_interface/ --count --show-source --statistics
        flake8 tests/ --count --show-source --statistics
        flake8 setup.py --count --show-source --statistics
    - name: Test with pytest
      run: ./scripts/test.sh
